version: "3.8"

services:
  # Google Maps Crawler
  crawler:
    build: .
    container_name: google_maps_crawler
    environment:
      # Database connection - sử dụng database có sẵn trên server
      DB_HOST: 163.223.8.12
      DB_PORT: 5432
      DB_USER: cdudu
      DB_PASSWORD: cdudu.com
      DB_NAME: google-map-data
      DB_SSL_MODE: disable

      # Chrome settings
      DISPLAY: :99
      PYTHONUNBUFFERED: 1
    volumes:
      - ./logs:/app/logs
      - ./list_jobs.txt:/app/list_jobs.txt
    restart: unless-stopped
